### ISSUE TITLE
Feature request: intensifies

### ISSUE THREAD

**Issue by toriagibbs-zz** [yacomink/inyourface#11]
Make 'em shake

**Comment by ieatkillerbees** [comment]
:+1: please implement asap my family is dying

**Comment by yacomink** [comment]
![download](https://user-images.githubusercontent.com/438574/46103572-28024b80-c19f-11e8-8952-f8d0e7939703.gif)

**Comment by roblaplaca** [comment]
💯

**Comment by toriagibbs-zz** [comment]
For future reference: http://chrisvalleskey.com/labs/intensifier/

**Comment by goldsamantha** [comment]
👌 i almost had an attack while making gifs with that thing just now

**Comment by yacomink** [comment]
Ok, I added a new Intensifies effect!
